/**
 * Compliance Export Routes
 *
 * GET /api/pipeline/:runId/export?format=json   → downloadable JSON compliance artifact
 * GET /api/pipeline/:runId/export?format=pdf    → downloadable PDF compliance report
 *
 * Every pipeline run produces a structured, exportable compliance report that
 * an auditor can hold. This turns BuildOrbit's glass-box pipeline from a
 * marketing claim into enterprise-grade evidence.
 */

'use strict';

const express = require('express');
const crypto  = require('crypto');
const fs      = require('fs');
const path    = require('path');

// ── Constants ─────────────────────────────────────────────────────────────────

const PIPELINE_VERSION = '1.0';
const PHASES_ORDER     = ['intent_gate', 'plan', 'scaffold', 'code', 'save', 'verify'];

// ── Factory ───────────────────────────────────────────────────────────────────

/**
 * @param {{ pool, artifactStore, pipeline, requireAuth }} deps
 * @returns {express.Router}
 */
function createComplianceExportRouter({ pool, artifactStore, pipeline, requireAuth }) {
  const router = express.Router();

  // Auth guard: if requireAuth provided, apply it; otherwise use a soft check.
  const authMiddleware = requireAuth || ((req, res, next) => {
    if (!req.user?.userId) {
      return res.status(401).json({ success: false, message: 'Authentication required' });
    }
    next();
  });

  // ── GET /api/pipeline/:runId/code-files/download ────────────────────────
  // Download the generated project as a ZIP archive.
  // React CDN builds: index.html + app.jsx + components/ + package.json.
  // Standard builds: all generated files as-is.
  router.get('/:runId/code-files/download', authMiddleware, async (req, res) => {
    try {
      const { runId } = req.params;
      const userId = req.user?.userId || null;

      if (!/^[0-9a-f-]{36}$/i.test(runId)) {
        return res.status(400).json({ success: false, message: 'Invalid run ID' });
      }

      // Ownership check — always scope by user
      if (!userId) {
        return res.status(401).json({ success: false, message: 'Authentication required' });
      }
      const ownerRow = await pool.query(
        `SELECT id FROM pipeline_runs WHERE id = $1 AND user_id = $2`,
        [runId, userId]
      );
      if (ownerRow.rows.length === 0) {
        return res.status(404).json({ success: false, message: 'Run not found' });
      }

      // Load code artifact — filesystem first, DB fallback
      let codeArtifact = await artifactStore.readArtifact(runId, 'code', 'code.json');
      if (!codeArtifact || !codeArtifact.files) {
        try {
          const { rows } = await pool.query(`SELECT code FROM pipeline_runs WHERE id = $1`, [runId]);
          if (rows[0]?.code) {
            codeArtifact = typeof rows[0].code === 'string' ? JSON.parse(rows[0].code) : rows[0].code;
          }
        } catch (_) { /* fall through */ }
      }

      if (!codeArtifact || !codeArtifact.files || Object.keys(codeArtifact.files).length === 0) {
        return res.status(404).json({ success: false, message: 'No generated files for this run' });
      }

      const files = { ...codeArtifact.files };
      const isReact = Object.keys(files).some(k => k === 'app.jsx' || k.endsWith('/app.jsx'));

      // Inject package.json for React CDN builds if not already present
      if (isReact && !files['package.json']) {
        files['package.json'] = JSON.stringify({
          name: 'buildorbit-app',
          version: '1.0.0',
          description: 'Generated by BuildOrbit — https://buildorbit.polsia.app',
          scripts: { start: 'npx serve . -l 3000' },
          devDependencies: { serve: '^14.0.0' },
          readme: 'Open index.html in a browser, or: npm install && npm start',
        }, null, 2);
      }

      const zipBuf = buildZip(files);
      const slug = runId.slice(0, 8);
      const zipName = isReact ? `buildorbit-react-${slug}.zip` : `buildorbit-${slug}.zip`;

      res.set({
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${zipName}"`,
        'Content-Length': zipBuf.length,
      });
      res.send(zipBuf);
      console.log(`[ComplianceExport] ZIP download: ${zipName} (${Object.keys(files).length} files, ${zipBuf.length}B)`);
    } catch (err) {
      console.error('[ComplianceExport] ZIP download error:', err.message);
      res.status(500).json({ success: false, message: 'Failed to create download' });
    }
  });

  // ── GET /api/pipeline/:runId/export ─────────────────────────────────────
  router.get('/:runId/export', authMiddleware, async (req, res) => {
    try {
      const { runId }  = req.params;
      const format     = (req.query.format || 'json').toLowerCase();
      const userId     = req.user?.userId || null;

      // ── UUID guard ──────────────────────────────────────────────────────
      if (!/^[0-9a-f-]{36}$/i.test(runId)) {
        return res.status(400).json({ success: false, message: 'Invalid run ID' });
      }

      // ── Fetch run (ownership enforced — always scope by user) ────────────
      if (!userId) {
        return res.status(401).json({ success: false, message: 'Authentication required' });
      }
      const runRow = await pool.query(
        `SELECT id, prompt, status, state, intent_class,
                plan, scaffold, code, output, verification,
                created_at, completed_at, run_config, execution_id
           FROM pipeline_runs
          WHERE id = $1
            AND user_id = $2`,
        [runId, userId]
      );
      if (runRow.rows.length === 0) {
        return res.status(404).json({ success: false, message: 'Run not found' });
      }
      const run = runRow.rows[0];

      // ── Terminal status guard ───────────────────────────────────────────
      const TERMINAL = ['completed', 'failed', 'error', 'cancelled'];
      if (!TERMINAL.includes(run.status)) {
        return res.status(409).json({
          success: false,
          message: `Run is not yet complete (status: ${run.status}). Export only available after the run finishes.`,
        });
      }

      // ── Fetch pipeline events (phase timeline) ──────────────────────────
      const eventsRow = await pool.query(
        `SELECT stage, status, payload, error, created_at
           FROM pipeline_events
          WHERE run_id = $1
          ORDER BY created_at ASC`,
        [runId]
      );
      const events = eventsRow.rows;

      // ── Fetch constraint prediction (Intent Gate) ───────────────────────
      const predRow = await pool.query(
        `SELECT task_type, predicted_constraints, confidence, entropy, candidates, committed, created_at
           FROM constraint_predictions
          WHERE run_id = $1
          ORDER BY created_at DESC LIMIT 1`,
        [runId]
      );
      const prediction = predRow.rows[0] || null;

      // ── Fetch constraint violations (rejections) ────────────────────────
      const violRow = await pool.query(
        `SELECT violation_type, violated_layer, severity, created_at
           FROM constraint_violations
          WHERE run_id = $1
          ORDER BY severity DESC`,
        [runId]
      );
      const violations = violRow.rows;

      // ── Fetch decisions log (classification reasoning) ──────────────────
      const decRow = await pool.query(
        `SELECT input_text, classified_task_type, final_constraints, adjustments_applied, created_at
           FROM constraint_decisions_log
          WHERE run_id = $1
          ORDER BY created_at DESC LIMIT 1`,
        [runId]
      );
      const decision = decRow.rows[0] || null;

      // ── Artifacts with SHA-256 hashes ───────────────────────────────────
      const rawArtifacts = await artifactStore.listArtifacts(runId).catch(() => []);
      const artifactsProduced = rawArtifacts.map(a => {
        const filePath = path.join('./artifacts', runId, a.stage, a.filename);
        let hash = null;
        try {
          if (fs.existsSync(filePath)) {
            hash = 'sha256:' + crypto
              .createHash('sha256')
              .update(fs.readFileSync(filePath))
              .digest('hex');
          }
        } catch (_) { /* non-fatal */ }
        return {
          filename: a.filename,
          stage:    a.stage,
          size:     a.size,
          hash,
        };
      });

      // ── Build phase timeline ─────────────────────────────────────────────
      // Group events by stage → derive start/end timestamps, duration, status
      const phaseMap = {};
      for (const evt of events) {
        const s = (evt.stage || '').toLowerCase();
        if (!phaseMap[s]) phaseMap[s] = { started: null, ended: null, status: null, payloads: [] };
        const ts = evt.created_at ? new Date(evt.created_at).toISOString() : null;
        if (evt.status === 'started' || evt.status === 'running') {
          if (!phaseMap[s].started) phaseMap[s].started = ts;
        } else if (evt.status === 'completed' || evt.status === 'failed') {
          phaseMap[s].ended  = ts;
          phaseMap[s].status = evt.status;
        }
        if (evt.payload) phaseMap[s].payloads.push(evt.payload);
      }

      const phases = PHASES_ORDER
        .filter(p => phaseMap[p])
        .map(p => {
          const ph = phaseMap[p];
          const durationMs = (ph.started && ph.ended)
            ? new Date(ph.ended) - new Date(ph.started)
            : null;
          // Extract a brief output summary from the last payload
          const lastPayload = ph.payloads[ph.payloads.length - 1];
          const outputSummary = extractOutputSummary(p, lastPayload, run);
          return {
            phase:          p.toUpperCase(),
            status:         ph.status || 'unknown',
            timestamp_start: ph.started,
            timestamp_end:   ph.ended,
            duration_ms:     durationMs,
            output_summary:  outputSummary,
          };
        });

      // ── Parse verify results ─────────────────────────────────────────────
      const verifyResults = parseVerifyResults(run.verification, events);

      // ── Parse run_config for model routing ──────────────────────────────
      const runConfig = safeParseJson(run.run_config);
      const modelRouting = buildModelRouting(runConfig, run.intent_class);

      // ── Parse product context ────────────────────────────────────────────
      const productContext = runConfig?.productContext || null;

      // ── Build rejections list ────────────────────────────────────────────
      const rejections = buildRejections(violations, events);

      // ── Build Intent Gate block ──────────────────────────────────────────
      const intentGate = buildIntentGate(prediction, decision, run);

      // ── Assemble final compliance artifact ──────────────────────────────
      const report = {
        run_id:          run.id,
        execution_id:    run.execution_id || null,
        timestamp_start: run.created_at ? new Date(run.created_at).toISOString() : null,
        timestamp_end:   run.completed_at ? new Date(run.completed_at).toISOString() : null,
        duration_ms:     (run.created_at && run.completed_at)
          ? new Date(run.completed_at) - new Date(run.created_at) : null,
        overall_status:  run.status,
        user_prompt:     run.prompt,
        product_context: productContext,
        intent_gate:     intentGate,
        phases,
        verify_results:  verifyResults,
        rejections,
        artifacts_produced: artifactsProduced,
        model_routing:   modelRouting,
        generated_by:    `BuildOrbit Pipeline v${PIPELINE_VERSION}`,
        generated_at:    new Date().toISOString(),
      };

      // ── Format dispatch ──────────────────────────────────────────────────
      if (format === 'pdf') {
        const pdfBuffer = await buildPdf(report);
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition',
          `attachment; filename="buildorbit-run-${runId.slice(0, 8)}-report.pdf"`);
        return res.send(pdfBuffer);
      }

      // Default: JSON
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition',
        `attachment; filename="buildorbit-run-${runId.slice(0, 8)}-report.json"`);
      return res.json(report);

    } catch (err) {
      console.error('[ComplianceExport] Error:', err);
      res.status(500).json({ success: false, message: 'Failed to generate compliance report' });
    }
  });

  return router;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function safeParseJson(val) {
  if (!val) return null;
  try {
    return typeof val === 'string' ? JSON.parse(val) : val;
  } catch (_) {
    return null;
  }
}

function extractOutputSummary(phase, payload, run) {
  if (!payload) {
    // Fall back to run columns
    if (phase === 'plan')     return summariseObject(safeParseJson(run.plan));
    if (phase === 'scaffold') return summariseObject(safeParseJson(run.scaffold));
    if (phase === 'code')     return summariseObject(safeParseJson(run.code));
    if (phase === 'verify')   return summariseObject(safeParseJson(run.verification));
    return null;
  }
  const p = typeof payload === 'string' ? safeParseJson(payload) : payload;
  if (!p) return null;
  // Common summary fields
  if (p.summary)       return String(p.summary).slice(0, 300);
  if (p.description)   return String(p.description).slice(0, 300);
  if (p.output_summary) return String(p.output_summary).slice(0, 300);
  return summariseObject(p);
}

function summariseObject(obj) {
  if (!obj) return null;
  const s = JSON.stringify(obj);
  return s.length > 300 ? s.slice(0, 297) + '…' : s;
}

function parseVerifyResults(verificationCol, events) {
  // Try column first
  const v = safeParseJson(verificationCol);
  if (v && (v.checks || v.overall_status)) {
    const checks = (v.checks || []).map(c => ({
      name:     c.name || c.check || 'Check',
      status:   c.passed === true ? 'passed' : c.passed === false ? 'failed' : (c.status || 'unknown'),
      terminal: c.terminal || false,
      details:  c.details || c.reason || null,
    }));
    return {
      overall_status: v.overall_status || (checks.every(c => c.status !== 'failed') ? 'passed' : 'failed'),
      checks,
    };
  }

  // Try to reconstruct from events
  const verifyEvents = events.filter(e => e.stage === 'verify');
  if (verifyEvents.length === 0) return { overall_status: 'unknown', checks: [] };
  const last = verifyEvents[verifyEvents.length - 1];
  const p = typeof last.payload === 'string' ? safeParseJson(last.payload) : (last.payload || {});
  const checks = (p?.checks || []).map(c => ({
    name:     c.name || 'Check',
    status:   c.passed === true ? 'passed' : c.passed === false ? 'failed' : (c.status || 'unknown'),
    terminal: c.terminal || false,
    details:  c.details || null,
  }));
  return {
    overall_status: last.status === 'completed' ? 'passed' : 'failed',
    checks,
  };
}

function buildModelRouting(runConfig, intentClass) {
  const models = runConfig?.models || {};
  const planModel  = models.planner || models.plan  || 'gpt-4o-mini';
  const buildModel = models.builder || models.code  || 'gpt-4o-mini';
  const qaModel    = models.qa     || models.verify || 'gpt-4o-mini';
  const codeModel  = intentClass === 'PRODUCT_SYSTEM' ? 'claude-sonnet-4-20250514' : buildModel;
  const routingReason = intentClass
    ? `intent_class=${intentClass} → ${codeModel}`
    : 'default routing';
  return {
    plan_model:     planModel,
    code_model:     codeModel,
    qa_model:       qaModel,
    routing_reason: routingReason,
  };
}

function buildRejections(violations, events) {
  const rejections = [];

  // From constraint violations table
  for (const v of violations) {
    rejections.push({
      phase:  'VERIFY',
      reason: `${v.violation_type} — ${v.violated_layer} (severity: ${v.severity})`,
      timestamp: v.created_at ? new Date(v.created_at).toISOString() : null,
    });
  }

  // From pipeline events with failed status and non-empty error
  for (const e of events) {
    if (e.status === 'failed' && e.error) {
      rejections.push({
        phase:     (e.stage || '').toUpperCase(),
        reason:    e.error,
        timestamp: e.created_at ? new Date(e.created_at).toISOString() : null,
      });
    }
  }

  return rejections;
}

function buildIntentGate(prediction, decision, run) {
  const intentClass = run.intent_class || prediction?.task_type || null;
  let constraintContract = null;

  if (prediction?.predicted_constraints) {
    const c = typeof prediction.predicted_constraints === 'string'
      ? safeParseJson(prediction.predicted_constraints)
      : prediction.predicted_constraints;
    constraintContract = c || null;
  }

  // Try to reconstruct from decision log if prediction is missing/incomplete
  if (!constraintContract && decision?.final_constraints) {
    const c = typeof decision.final_constraints === 'string'
      ? safeParseJson(decision.final_constraints)
      : decision.final_constraints;
    constraintContract = c || null;
  }

  const classificationReasoning = decision?.adjustments_applied
    ? (typeof decision.adjustments_applied === 'string'
        ? decision.adjustments_applied
        : JSON.stringify(decision.adjustments_applied))
    : null;

  return {
    intent_class:              intentClass,
    constraint_contract:       constraintContract,
    classification_confidence: prediction?.confidence || null,
    classification_reasoning:  classificationReasoning,
  };
}

// ── PDF Builder ───────────────────────────────────────────────────────────────

async function buildPdf(report) {
  // Lazy-load pdfkit so missing dep fails gracefully at request time
  let PDFDocument;
  try {
    PDFDocument = require('pdfkit');
  } catch (_) {
    throw new Error('pdfkit is not installed. Run: npm install pdfkit');
  }

  return new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 50, size: 'A4', autoFirstPage: true });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end',  () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const W      = doc.page.width  - 100; // usable width
    const LEFT   = 50;
    const ACCENT = '#0EA5E9'; // BuildOrbit blue
    const DARK   = '#1A202C';
    const DIM    = '#718096';
    const LIGHT  = '#F7FAFC';

    // ── Header ─────────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill(DARK);
    doc.fillColor('white').fontSize(18).font('Helvetica-Bold')
       .text('BuildOrbit Compliance Report', LEFT, 20);
    doc.fontSize(9).font('Helvetica').fillColor('#A0AEC0')
       .text(`Run ID: ${report.run_id}`, LEFT, 45)
       .text(`Generated: ${report.generated_at}`, LEFT, 57);
    doc.moveDown(3);

    // ── Status Badge ───────────────────────────────────────────────────────
    const statusColor = report.overall_status === 'completed' ? '#38A169' :
                        report.overall_status === 'failed'    ? '#E53E3E' : '#DD6B20';
    doc.rect(LEFT, doc.y, 90, 22).fill(statusColor);
    doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
       .text(report.overall_status.toUpperCase(), LEFT + 5, doc.y - 18, { width: 80, align: 'center' });
    doc.moveDown(1.5);

    // ── Run Summary ─────────────────────────────────────────────────────────
    pdfSectionHeader(doc, '🔎 Run Summary', ACCENT, LEFT, W);
    const durationSec = report.duration_ms != null
      ? (report.duration_ms / 1000).toFixed(1) + 's'
      : 'n/a';
    pdfLabelValue(doc, 'Execution ID',  report.execution_id || report.run_id, LEFT);
    pdfLabelValue(doc, 'Start',         report.timestamp_start || 'n/a', LEFT);
    pdfLabelValue(doc, 'End',           report.timestamp_end || 'n/a', LEFT);
    pdfLabelValue(doc, 'Duration',      durationSec, LEFT);
    pdfLabelValue(doc, 'Prompt',        (report.user_prompt || 'n/a').slice(0, 200), LEFT);

    // ── Section 1 — Intent Gate ─────────────────────────────────────────────
    pdfSectionHeader(doc, 'Section 1 — Intent Gate', ACCENT, LEFT, W);
    const ig = report.intent_gate || {};
    pdfLabelValue(doc, 'Intent Class',   ig.intent_class || 'n/a', LEFT);
    pdfLabelValue(doc, 'Confidence',
      ig.classification_confidence != null
        ? (ig.classification_confidence * 100).toFixed(1) + '%'
        : 'n/a', LEFT);
    if (ig.classification_reasoning) {
      pdfLabelValue(doc, 'Reasoning', ig.classification_reasoning.slice(0, 400), LEFT);
    }
    if (ig.constraint_contract) {
      doc.fontSize(9).font('Helvetica-Bold').fillColor(DARK)
         .text('Constraint Contract:', LEFT, doc.y, { continued: false });
      const ccStr = JSON.stringify(ig.constraint_contract, null, 2);
      doc.fontSize(7.5).font('Courier').fillColor('#2D3748')
         .text(ccStr.slice(0, 800) + (ccStr.length > 800 ? '\n…' : ''),
               LEFT + 10, doc.y, { width: W - 10 });
      doc.moveDown(0.5);
    }

    // ── Section 2 — Phase Timeline ──────────────────────────────────────────
    pdfSectionHeader(doc, 'Section 2 — Phase Timeline', ACCENT, LEFT, W);
    if (report.phases.length === 0) {
      doc.fontSize(9).font('Helvetica').fillColor(DIM).text('No phase data recorded.', LEFT);
    } else {
      for (const ph of report.phases) {
        const statusIcon = ph.status === 'completed' ? '✓' : ph.status === 'failed' ? '✗' : '○';
        const dur = ph.duration_ms != null ? ` (${(ph.duration_ms / 1000).toFixed(1)}s)` : '';
        const phaseColor = ph.status === 'completed' ? '#38A169' : ph.status === 'failed' ? '#E53E3E' : DIM;
        doc.fontSize(9.5).font('Helvetica-Bold').fillColor(phaseColor)
           .text(`${statusIcon} ${ph.phase}${dur}`, LEFT, doc.y);
        doc.fontSize(8).font('Helvetica').fillColor(DIM)
           .text(`  Start: ${ph.timestamp_start || 'n/a'}  →  End: ${ph.timestamp_end || 'n/a'}`,
                 LEFT + 10, doc.y, { width: W - 10 });
        if (ph.output_summary) {
          doc.fontSize(7.5).font('Helvetica').fillColor('#4A5568')
             .text(`  ${ph.output_summary.slice(0, 200)}`,
                   LEFT + 10, doc.y, { width: W - 10 });
        }
        doc.moveDown(0.4);
      }
    }

    // ── Section 3 — Verification Results ────────────────────────────────────
    pdfSectionHeader(doc, 'Section 3 — Verification Results', ACCENT, LEFT, W);
    const vr = report.verify_results || {};
    const vrStatus = vr.overall_status || 'unknown';
    const vrColor  = vrStatus === 'passed' ? '#38A169' : vrStatus === 'failed' ? '#E53E3E' : DIM;
    doc.fontSize(10).font('Helvetica-Bold').fillColor(vrColor)
       .text(`Overall: ${vrStatus.toUpperCase()}`, LEFT);
    doc.moveDown(0.3);
    const checks = vr.checks || [];
    if (checks.length === 0) {
      doc.fontSize(8).font('Helvetica').fillColor(DIM).text('No verification checks recorded.', LEFT);
    } else {
      for (const chk of checks) {
        const icon  = chk.status === 'passed' ? '✓' : chk.status === 'failed' ? '✗' : '△';
        const color = chk.status === 'passed' ? '#38A169' : chk.status === 'failed' ? '#E53E3E' : '#DD6B20';
        const term  = chk.terminal ? ' [terminal]' : '';
        doc.fontSize(8.5).font('Helvetica').fillColor(color)
           .text(`  ${icon} ${chk.name}${term}`, LEFT, doc.y, { width: W });
        if (chk.details) {
          doc.fontSize(7.5).fillColor('#718096')
             .text(`     ${String(chk.details).slice(0, 200)}`, LEFT + 10, doc.y, { width: W - 10 });
        }
        doc.moveDown(0.25);
      }
    }

    // ── Section 4 — Rejections & Warnings ───────────────────────────────────
    pdfSectionHeader(doc, 'Section 4 — Rejections & Warnings', ACCENT, LEFT, W);
    if (report.rejections.length === 0) {
      doc.fontSize(8.5).font('Helvetica').fillColor('#38A169').text('No rejections or warnings.', LEFT);
    } else {
      for (const r of report.rejections) {
        doc.fontSize(8.5).font('Helvetica').fillColor('#E53E3E')
           .text(`  ✗ [${r.phase}] ${r.reason.slice(0, 200)}`, LEFT, doc.y, { width: W });
        if (r.timestamp) {
          doc.fontSize(7).fillColor(DIM)
             .text(`     ${r.timestamp}`, LEFT + 10, doc.y, { width: W - 10 });
        }
        doc.moveDown(0.3);
      }
    }

    // ── Section 5 — Artifacts ────────────────────────────────────────────────
    pdfSectionHeader(doc, 'Section 5 — Artifacts', ACCENT, LEFT, W);
    if (report.artifacts_produced.length === 0) {
      doc.fontSize(8.5).font('Helvetica').fillColor(DIM).text('No artifacts recorded.', LEFT);
    } else {
      for (const a of report.artifacts_produced) {
        doc.fontSize(8.5).font('Helvetica').fillColor(DARK)
           .text(`  📄 ${a.filename}`, LEFT, doc.y, { width: W });
        doc.fontSize(7.5).font('Courier').fillColor(DIM)
           .text(`     Hash: ${a.hash || 'n/a'}  ·  Size: ${a.size || 0} bytes  ·  Stage: ${a.stage}`,
                 LEFT + 10, doc.y, { width: W - 10 });
        doc.moveDown(0.3);
      }
    }

    // ── Model Routing ────────────────────────────────────────────────────────
    pdfSectionHeader(doc, 'Model Routing', ACCENT, LEFT, W);
    const mr = report.model_routing || {};
    pdfLabelValue(doc, 'Plan Model',    mr.plan_model    || 'n/a', LEFT);
    pdfLabelValue(doc, 'Code Model',    mr.code_model    || 'n/a', LEFT);
    pdfLabelValue(doc, 'QA Model',      mr.qa_model      || 'n/a', LEFT);
    pdfLabelValue(doc, 'Routing',       mr.routing_reason || 'n/a', LEFT);

    // ── Footer ───────────────────────────────────────────────────────────────
    const footerY = doc.page.height - 40;
    doc.rect(0, footerY - 10, doc.page.width, 50).fill(DARK);
    doc.fillColor('#A0AEC0').fontSize(7.5).font('Helvetica')
       .text(
         `Generated by BuildOrbit Pipeline v${PIPELINE_VERSION} — immutable record · ${report.generated_at}`,
         LEFT, footerY, { width: W, align: 'center' }
       );

    doc.end();
  });
}

/** Renders a bold section header with a colored rule. */
function pdfSectionHeader(doc, title, color, left, width) {
  doc.moveDown(0.6);
  doc.rect(left, doc.y, width, 1).fill(color);
  doc.moveDown(0.3);
  doc.fontSize(11).font('Helvetica-Bold').fillColor(color)
     .text(title, left, doc.y);
  doc.moveDown(0.3);
}

/** Renders a "Label: Value" row. */
function pdfLabelValue(doc, label, value, left) {
  doc.fontSize(8.5).font('Helvetica-Bold').fillColor('#2D3748')
     .text(`${label}: `, left, doc.y, { continued: true, width: 120 });
  doc.font('Helvetica').fillColor('#4A5568')
     .text(String(value || 'n/a'), { width: 380 });
  doc.moveDown(0.2);
}

// ── Helpers: CRC32 + ZIP builder ──────────────────────────────────────────────

/** CRC32 table (PKZIP standard). */
const CRC32_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
    t[i] = c >>> 0;
  }
  return t;
})();

function crc32(buf) {
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i++) crc = (CRC32_TABLE[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8)) >>> 0;
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(n) { const b = Buffer.alloc(2); b.writeUInt16LE(n, 0); return b; }
function u32(n) { const b = Buffer.alloc(4); b.writeUInt32LE(n >>> 0, 0); return b; }

/**
 * Build a minimal ZIP buffer from an object of { path → string content }.
 * Uses zlib deflate where it saves bytes, store otherwise.
 * No external dependencies — Node.js core only.
 *
 * @param {Record<string, string|Buffer>} files
 * @returns {Buffer}
 */
function buildZip(files) {
  const zlib = require('zlib');
  const MOD_DATE = 0x5400; // 2022-10-00 (static — reproducible builds)
  const MOD_TIME = 0x0000;

  const localHeaders = [];
  const centralHeaders = [];
  let offset = 0;

  for (const [fileName, content] of Object.entries(files)) {
    const nameBuf = Buffer.from(fileName, 'utf8');
    const contentBuf = Buffer.isBuffer(content) ? content : Buffer.from(String(content), 'utf8');
    const deflated = zlib.deflateRawSync(contentBuf, { level: 6 });
    const useDef = deflated.length < contentBuf.length;
    const dataBuf = useDef ? deflated : contentBuf;
    const method = useDef ? 8 : 0;
    const crc = crc32(contentBuf);

    const local = Buffer.concat([
      Buffer.from([0x50, 0x4b, 0x03, 0x04]),
      u16(20), u16(0), u16(method), u16(MOD_TIME), u16(MOD_DATE),
      u32(crc), u32(dataBuf.length), u32(contentBuf.length),
      u16(nameBuf.length), u16(0), nameBuf, dataBuf,
    ]);

    const central = Buffer.concat([
      Buffer.from([0x50, 0x4b, 0x01, 0x02]),
      u16(20), u16(20), u16(0), u16(method), u16(MOD_TIME), u16(MOD_DATE),
      u32(crc), u32(dataBuf.length), u32(contentBuf.length),
      u16(nameBuf.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset),
      nameBuf,
    ]);

    localHeaders.push(local);
    centralHeaders.push(central);
    offset += local.length;
  }

  const centralDir = Buffer.concat(centralHeaders);
  const eocd = Buffer.concat([
    Buffer.from([0x50, 0x4b, 0x05, 0x06]),
    u16(0), u16(0),
    u16(localHeaders.length), u16(localHeaders.length),
    u32(centralDir.length), u32(offset), u16(0),
  ]);

  return Buffer.concat([...localHeaders, centralDir, eocd]);
}

// ── Exports ───────────────────────────────────────────────────────────────────

module.exports = { createComplianceExportRouter, buildZip };
