/**
 * GitHub Push Service
 *
 * Owns: pushing generated project files to a GitHub repo as a Pull Request.
 * Not owned: GitHub OAuth, repo listing, user connection management (routes/github.js).
 *
 * Responsibilities:
 *   - Decrypt the user's stored GitHub token
 *   - Create (or ensure) the target repo exists
 *   - Get the default branch SHA
 *   - Create a new branch `buildorbit/{runId}`
 *   - Commit all generated files via Contents API
 *   - Open a PR from the branch to the default branch
 *   - Return the PR URL for storage in pipeline_runs
 *
 * Edge cases handled:
 *   - Empty repo (no default branch yet) → creates initial README commit first
 *   - Token expired → throws with code TOKEN_EXPIRED for caller to surface
 *   - Large files → GitHub blocks files >100MB; each file checked before upload
 *   - Rate limits → GitHub 403/429 surfaced as GitHubRateLimitError
 */

'use strict';

const crypto = require('crypto');

// ── Token decryption ──────────────────────────────────────────────────────────
// Key derived from JWT_SECRET — must be set (validated at startup by auth module).
function getEncKey() {
  if (!process.env.JWT_SECRET) {
    throw new Error('FATAL: JWT_SECRET env var required for token decryption');
  }
  return crypto.createHash('sha256').update(process.env.JWT_SECRET).digest(); // 32 bytes
}

function decryptToken(enc) {
  const [ivHex, tagHex, ctHex] = enc.split(':');
  const key = getEncKey();
  const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(ivHex, 'hex'));
  decipher.setAuthTag(Buffer.from(tagHex, 'hex'));
  return decipher.update(Buffer.from(ctHex, 'hex'), null, 'utf8') + decipher.final('utf8');
}

// ── GitHub API helpers ────────────────────────────────────────────────────────
const GH_BASE = 'https://api.github.com';
const GH_VERSION = '2022-11-28';

function ghHeaders(token) {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': GH_VERSION,
    'Content-Type': 'application/json',
  };
}

/**
 * Lightweight fetch wrapper for GitHub REST API calls.
 * Throws a structured error on non-2xx responses.
 */
async function ghFetch(token, method, path, body = null) {
  const opts = {
    method,
    headers: ghHeaders(token),
  };
  if (body !== null) {
    opts.body = JSON.stringify(body);
  }

  const res = await fetch(`${GH_BASE}${path}`, opts);

  if (res.status === 401) {
    const err = new Error('GitHub token expired or revoked');
    err.code = 'TOKEN_EXPIRED';
    throw err;
  }

  if (res.status === 403 || res.status === 429) {
    const err = new Error(`GitHub rate limit or permission error (HTTP ${res.status})`);
    err.code = 'RATE_LIMITED';
    throw err;
  }

  if (res.status === 404) {
    const err = new Error(`GitHub resource not found: ${path}`);
    err.code = 'NOT_FOUND';
    throw err;
  }

  if (!res.ok && res.status !== 422) {
    const body = await res.text().catch(() => '');
    const err = new Error(`GitHub API error ${res.status}: ${body.slice(0, 200)}`);
    err.code = 'GH_API_ERROR';
    err.status = res.status;
    throw err;
  }

  const json = await res.json();
  return { status: res.status, data: json };
}

// ── File size gate ────────────────────────────────────────────────────────────
const MAX_FILE_BYTES = 99 * 1024 * 1024; // 99 MB — GitHub hard cap is 100MB

function filterOversizedFiles(files) {
  const safe = {};
  const skipped = [];
  for (const [path, content] of Object.entries(files)) {
    const bytes = Buffer.byteLength(content, 'utf8');
    if (bytes > MAX_FILE_BYTES) {
      skipped.push(`${path} (${Math.round(bytes / 1024 / 1024)}MB)`);
    } else {
      safe[path] = content;
    }
  }
  return { safe, skipped };
}

// ── Branch name helpers ───────────────────────────────────────────────────────

/**
 * Generates a clean branch name from the run ID.
 * Format: buildorbit/{first-8-chars-of-runId}
 */
function makeBranchName(runId) {
  return `buildorbit/${runId.slice(0, 8)}`;
}

// ── PR description template ───────────────────────────────────────────────────

function buildPrBody({ prompt, intentClass, files }) {
  const fileList = Object.keys(files)
    .slice(0, 20) // cap at 20 to keep PR description readable
    .map(f => `- \`${f}\``)
    .join('\n');

  const archetypeLabel = intentClass
    ? intentClass.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    : 'Auto-detected';

  return `## 🚀 Generated by BuildOrbit

**Prompt:** "${prompt}"
**Archetype:** ${archetypeLabel}
**Pipeline:** Intent Gate ✓ → Plan ✓ → Scaffold ✓ → Code ✓ → Save ✓ → Verify ✓

### Files
${fileList}
${Object.keys(files).length > 20 ? `\n_...and ${Object.keys(files).length - 20} more files_` : ''}

### Run Locally
\`\`\`bash
npm install
npm start
\`\`\`

Built with [BuildOrbit](https://buildorbit.polsia.app) — the autonomous app builder that shows its work.`;
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Push generated project files to a GitHub PR.
 *
 * @param {object} opts
 * @param {import('pg').Pool} opts.pool       - DB pool for reading github_connections
 * @param {number}  opts.userId               - User ID (for GitHub token lookup)
 * @param {string}  opts.runId                - Pipeline run UUID
 * @param {string}  opts.repoFullName         - "owner/repo" — e.g. "bry92/my-app"
 * @param {object}  opts.files                - { [filepath]: content } — generated files
 * @param {string}  opts.prompt               - Original user prompt (for PR title/body)
 * @param {string}  [opts.intentClass]        - Detected intent class (for PR body)
 * @param {boolean} [opts.createIfMissing]    - Create repo if it doesn't exist (default false)
 * @param {boolean} [opts.privateRepo]        - Private repo if creating (default false)
 *
 * @returns {Promise<{ prUrl: string, branchName: string, prNumber: number }>}
 */
async function pushToPR({ pool, userId, runId, repoFullName, files, prompt, intentClass, createIfMissing = false, privateRepo = false }) {
  // 1. Load encrypted token from DB
  const { rows } = await pool.query(
    'SELECT access_token_enc, github_login FROM github_connections WHERE user_id = $1',
    [userId]
  );

  if (!rows.length) {
    const err = new Error('GitHub not connected for this user');
    err.code = 'NOT_CONNECTED';
    throw err;
  }

  const token = decryptToken(rows[0].access_token_enc);
  const [owner, repo] = repoFullName.split('/');

  if (!owner || !repo) {
    throw new Error(`Invalid repo format: "${repoFullName}" — expected "owner/repo"`);
  }

  // 2. Filter oversized files
  const { safe: safeFiles, skipped } = filterOversizedFiles(files);
  if (skipped.length > 0) {
    console.warn(`[GitHubPush] Skipping ${skipped.length} oversized file(s): ${skipped.join(', ')}`);
  }

  if (Object.keys(safeFiles).length === 0) {
    throw new Error('No files to push (all files exceeded GitHub size limits)');
  }

  // 3. Get (or create) the repo and find default branch
  let defaultBranch;
  let baseSha;

  try {
    const { data: repoData } = await ghFetch(token, 'GET', `/repos/${owner}/${repo}`);
    defaultBranch = repoData.default_branch || 'main';
    console.log(`[GitHubPush] Repo ${repoFullName}: default branch = ${defaultBranch}`);
  } catch (err) {
    if (err.code === 'NOT_FOUND' && createIfMissing) {
      console.log(`[GitHubPush] Repo ${repoFullName} not found — creating...`);
      const { data: newRepo } = await ghFetch(token, 'POST', '/user/repos', {
        name: repo,
        private: Boolean(privateRepo),
        description: 'Created by BuildOrbit',
        auto_init: false,
      });
      defaultBranch = newRepo.default_branch || 'main';
    } else {
      throw err;
    }
  }

  // 4. Get the tip SHA of the default branch (needed to create our branch off it)
  //    Handle empty repos (no commits yet) by creating an initial commit.
  try {
    const { data: refData } = await ghFetch(token, 'GET', `/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`);
    baseSha = refData.object.sha;
  } catch (err) {
    if (err.code === 'NOT_FOUND') {
      // Empty repo — no commits yet. Create an initial README so we have a base SHA.
      console.log(`[GitHubPush] Empty repo — creating initial commit on ${defaultBranch}`);
      baseSha = await createInitialCommit(token, owner, repo, defaultBranch);
    } else {
      throw err;
    }
  }

  // 5. Create the new branch
  const branchName = makeBranchName(runId);
  const branchRef = `refs/heads/${branchName}`;

  // Check if branch already exists (retry scenario)
  let branchExists = false;
  try {
    await ghFetch(token, 'GET', `/repos/${owner}/${repo}/git/ref/heads/${branchName}`);
    branchExists = true;
    console.log(`[GitHubPush] Branch ${branchName} already exists — reusing`);
  } catch (e) {
    if (e.code !== 'NOT_FOUND') throw e;
  }

  if (!branchExists) {
    await ghFetch(token, 'POST', `/repos/${owner}/${repo}/git/refs`, {
      ref: branchRef,
      sha: baseSha,
    });
    console.log(`[GitHubPush] Created branch ${branchName} at ${baseSha.slice(0, 8)}`);
  }

  // 6. Commit all files to the branch using Contents API
  //    Each file is a PUT /repos/{owner}/{repo}/contents/{path}
  //    We do these sequentially to avoid racing SHA conflicts.
  let filesCommitted = 0;
  for (const [filePath, content] of Object.entries(safeFiles)) {
    const encodedContent = Buffer.from(content, 'utf8').toString('base64');
    const normalizedPath = filePath.replace(/^\//, ''); // strip leading slash

    // Check if file already exists on the branch (needed for the sha field on update)
    let existingSha = null;
    try {
      const { data: existing } = await ghFetch(token, 'GET', `/repos/${owner}/${repo}/contents/${normalizedPath}?ref=${branchName}`);
      existingSha = existing.sha;
    } catch (e) {
      if (e.code !== 'NOT_FOUND') throw e;
    }

    const filePayload = {
      message: `Add ${normalizedPath}`,
      content: encodedContent,
      branch: branchName,
    };
    if (existingSha) {
      filePayload.sha = existingSha;
    }

    await ghFetch(token, 'PUT', `/repos/${owner}/${repo}/contents/${normalizedPath}`, filePayload);
    filesCommitted++;
  }

  console.log(`[GitHubPush] Committed ${filesCommitted} file(s) to branch ${branchName}`);

  // 7. Add auto-generated README.md
  const readmeContent = buildReadme({ prompt, files: safeFiles, runId, intentClass });
  const readmeEncoded = Buffer.from(readmeContent, 'utf8').toString('base64');

  let readmeSha = null;
  try {
    const { data: existingReadme } = await ghFetch(token, 'GET', `/repos/${owner}/${repo}/contents/README.md?ref=${branchName}`);
    readmeSha = existingReadme.sha;
  } catch (e) {
    if (e.code !== 'NOT_FOUND') throw e;
  }

  const readmePayload = {
    message: 'Add README.md (generated by BuildOrbit)',
    content: readmeEncoded,
    branch: branchName,
  };
  if (readmeSha) readmePayload.sha = readmeSha;

  await ghFetch(token, 'PUT', `/repos/${owner}/${repo}/contents/README.md`, readmePayload);
  console.log(`[GitHubPush] README.md written to branch ${branchName}`);

  // 8. Open the PR
  const prTitle = `BuildOrbit: ${prompt.slice(0, 72)}${prompt.length > 72 ? '…' : ''}`;
  const prBody = buildPrBody({ prompt, intentClass, files: safeFiles });

  // Check if a PR for this branch already exists
  const { data: existingPRs } = await ghFetch(token, 'GET',
    `/repos/${owner}/${repo}/pulls?state=open&head=${owner}:${branchName}&base=${defaultBranch}`
  );

  let prData;
  if (existingPRs.length > 0) {
    prData = existingPRs[0];
    console.log(`[GitHubPush] PR already exists: #${prData.number} — ${prData.html_url}`);
  } else {
    const { data: newPR, status: prStatus } = await ghFetch(token, 'POST', `/repos/${owner}/${repo}/pulls`, {
      title: prTitle,
      body: prBody,
      head: branchName,
      base: defaultBranch,
    });

    if (prStatus === 422) {
      // 422 usually means "no commits between branches" — shouldn't happen but handle it
      const err = new Error('GitHub rejected PR creation (422 — no changes between branches?)');
      err.code = 'PR_REJECTED';
      throw err;
    }

    prData = newPR;
    console.log(`[GitHubPush] PR created: #${prData.number} — ${prData.html_url}`);
  }

  return {
    prUrl:      prData.html_url,
    prNumber:   prData.number,
    branchName,
    filesCommitted,
    skippedFiles: skipped,
  };
}

/**
 * Creates an initial commit on an empty repo so we have a base SHA to branch from.
 * Inserts a minimal README.md via the low-level Git data API.
 *
 * @returns {string} The SHA of the initial commit
 */
async function createInitialCommit(token, owner, repo, defaultBranch) {
  // Create a blob for the README
  const content = Buffer.from('# Project\n\nGenerated by [BuildOrbit](https://buildorbit.polsia.app).\n').toString('base64');
  const { data: blob } = await ghFetch(token, 'POST', `/repos/${owner}/${repo}/git/blobs`, {
    content,
    encoding: 'base64',
  });

  // Create a tree with the README
  const { data: tree } = await ghFetch(token, 'POST', `/repos/${owner}/${repo}/git/trees`, {
    tree: [{ path: 'README.md', mode: '100644', type: 'blob', sha: blob.sha }],
  });

  // Create the commit (no parent = first commit)
  const { data: commit } = await ghFetch(token, 'POST', `/repos/${owner}/${repo}/git/commits`, {
    message: 'Initial commit',
    tree: tree.sha,
    parents: [],
  });

  // Create/update the default branch ref
  try {
    await ghFetch(token, 'POST', `/repos/${owner}/${repo}/git/refs`, {
      ref: `refs/heads/${defaultBranch}`,
      sha: commit.sha,
    });
  } catch (err) {
    // If ref already exists, patch it
    if (err.code !== 'GH_API_ERROR') throw err;
    await ghFetch(token, 'PATCH', `/repos/${owner}/${repo}/git/refs/heads/${defaultBranch}`, {
      sha: commit.sha,
      force: false,
    });
  }

  return commit.sha;
}

/**
 * Builds an auto-generated README.md for the PR.
 */
function buildReadme({ prompt, files, runId, intentClass }) {
  const fileList = Object.keys(files)
    .slice(0, 20)
    .map(f => `- \`${f}\``)
    .join('\n');

  const archetypeLabel = intentClass
    ? intentClass.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
    : 'Auto-detected';

  return `# ${prompt.slice(0, 80)}${prompt.length > 80 ? '…' : ''}

> Generated by [BuildOrbit](https://buildorbit.polsia.app) — the autonomous app builder that shows its work.

## About

**Prompt:** ${prompt}
**Archetype:** ${archetypeLabel}
**Run ID:** \`${runId}\`

## Files

${fileList}
${Object.keys(files).length > 20 ? `\n_...and ${Object.keys(files).length - 20} more files_` : ''}

## Run Locally

\`\`\`bash
npm install
npm start
\`\`\`

The app starts on port 3000 by default. Set the \`DATABASE_URL\` environment variable for database-backed features.

## Pipeline

This app was generated through BuildOrbit's 6-phase glass-box pipeline:

1. **Intent Gate** — Classifies intent, locks constraint contract
2. **Plan** — Deterministic execution plan with task breakdown
3. **Scaffold** — File structure and dependency manifest
4. **Code** — Full implementation across all files
5. **Save** — Artifact persistence with audit hash
6. **Verify** — Automated quality checks (React wiring, DOM patterns, error handling)
`;
}

module.exports = { pushToPR };
