/**
 * Polsia Deploy Service
 *
 * Owns: Static app hosting for generated pipeline builds via Polsia R2 CDN.
 * Does NOT own: GitHub push (github-push.js), Node.js process management (node-app-runner.js).
 *
 * For STATIC_SURFACE and INTERACTIVE_LIGHT_APP builds, uploads all generated
 * HTML/CSS/JS files to R2 and returns a permanent CDN-hosted live URL.
 *
 * Files are stored under company_75550/{runId}/ and served at cdn.polsia.com.
 * The entry point (index.html or app.jsx-transpiled) becomes the live app URL.
 *
 * For PRODUCT_SYSTEM builds: returns null (full-stack apps require user-provisioned
 * hosting; the GitHub PR push handles code delivery).
 */

const FormData = require('form-data');
const nodeFetch = require('node-fetch');

const R2_UPLOAD_URL = 'https://polsia.com/api/proxy/r2/upload';

// MIME type map for files generated by BuildOrbit
const MIME_TYPES = {
  '.html': 'text/html',
  '.css':  'text/css',
  '.js':   'text/javascript',
  '.json': 'application/json',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.ico':  'image/x-icon',
  '.txt':  'text/plain',
  '.md':   'text/plain',
  '.ts':   'text/plain',
  '.tsx':  'text/plain',
  '.jsx':  'text/javascript',
};

/**
 * Deploy static build files to Polsia R2 CDN.
 *
 * @param {object} opts
 * @param {string} opts.runId         - Pipeline run UUID
 * @param {string} opts.intentClass   - 'STATIC_SURFACE' | 'INTERACTIVE_LIGHT_APP' | 'PRODUCT_SYSTEM'
 * @param {object} opts.files         - { [filename]: content_string } from pipeline code phase
 * @param {function} [opts.onProgress] - Optional progress callback: (msg) => void
 * @returns {Promise<{ liveUrl: string, fileCount: number } | null>}
 *   Returns null for PRODUCT_SYSTEM or if no uploadable files found.
 */
async function deployToPolsia({ runId, intentClass, files, onProgress }) {
  // Only deploy static/interactive builds — PRODUCT_SYSTEM needs real infra
  if (intentClass === 'PRODUCT_SYSTEM') {
    return null;
  }

  if (!files || Object.keys(files).length === 0) {
    return null;
  }

  const apiKey = process.env.POLSIA_API_KEY;
  if (!apiKey) {
    console.warn('[PolsiaDeploy] POLSIA_API_KEY not set — skipping R2 deploy');
    return null;
  }

  const path = require('path');
  const fileNames = Object.keys(files);

  // Find entry point: index.html preferred, then app.html, then first .html
  const entryFile = fileNames.find(f => f === 'index.html')
    || fileNames.find(f => f.endsWith('index.html'))
    || fileNames.find(f => f.endsWith('.html'))
    || null;

  if (!entryFile) {
    // No HTML entry point — skip (JSX-only builds handled by preview iframe, not CDN)
    return null;
  }

  const uploadedUrls = {};
  let successCount = 0;
  let entryUrl = null;

  if (onProgress) onProgress(`☁ Uploading ${fileNames.length} files to Polsia CDN...\n`);

  for (const fileName of fileNames) {
    const content = files[fileName];
    if (!content) continue;

    const ext = path.extname(fileName).toLowerCase();
    const mimeType = MIME_TYPES[ext] || 'text/plain';

    // Use a path like: {runId}/{fileName} so files within the same run share a namespace
    const uploadName = `${runId.replace(/-/g, '')}/${fileName}`;

    try {
      const buf = Buffer.from(content, 'utf8');
      const formData = new FormData();
      formData.append('file', buf, {
        filename: uploadName,
        contentType: mimeType,
      });

      const res = await nodeFetch(R2_UPLOAD_URL, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          ...formData.getHeaders(),
        },
        body: formData,
      });

      const result = await res.json();

      if (result.success && result.file && result.file.url) {
        uploadedUrls[fileName] = result.file.url;
        successCount++;
        if (fileName === entryFile) {
          entryUrl = result.file.url;
        }
      } else {
        console.warn(`[PolsiaDeploy] Upload failed for ${fileName}:`, result.error || result);
      }
    } catch (err) {
      console.warn(`[PolsiaDeploy] Upload error for ${fileName}:`, err.message);
    }
  }

  if (!entryUrl) {
    // Entry point upload failed — try any uploaded HTML
    const anyHtml = Object.entries(uploadedUrls).find(([k]) => k.endsWith('.html'));
    if (anyHtml) entryUrl = anyHtml[1];
  }

  if (!entryUrl) {
    console.warn('[PolsiaDeploy] No entry URL obtained — deploy skipped');
    return null;
  }

  if (onProgress) onProgress(`✓ Live app deployed: ${entryUrl}\n`);

  console.log(`[PolsiaDeploy] Run ${runId.slice(0,8)}: deployed ${successCount}/${fileNames.length} files. Entry: ${entryUrl}`);

  return {
    liveUrl: entryUrl,
    fileCount: successCount,
    allUrls: uploadedUrls,
  };
}

module.exports = { deployToPolsia };
